In [17]:
import os

using_colab = False
if using_colab:
  os.system('rm -rf ./*')
  os.system('git clone https://github.com/gasparyanartur/radio-optimizer.git')
  os.system('mv radio-optimizer/* ./')
  os.system('rm -rf radio-optimizer')

In [18]:
import numpy as np
from src.channel_mmWave_parameters import ChannelmmWaveParameters
from src.utils import db2pow

seed = 0
rng = np.random.default_rng(seed)

In [19]:
c = ChannelmmWaveParameters(
    PB = np.array([1, 2, 3]).reshape(-1, 1), 
    OB = np.array([45, 0, 0]).reshape(-1, 1),
    NB_dim = np.array([1, 1]).reshape(-1, 1),
    PR = np.array([[-5.01, 2, 0.5], [-1, 5.01, 0.5], [5.01, 2.5, 0.5]]).T,
    OR = np.array([[0, 0, 0], [-90, 0, 0], [180, 0, 0]]).T,
    NR_dim = np.array([[10, 10], [10, 10], [10, 10]]).T,
    PU = np.array([-2, 3, -1.5]).reshape(-1, 1),
    OU = np.array([0, 0, 0]).reshape(-1, 1),
    NU_dim = np.array([1, 1]).reshape(-1, 1),
    P = db2pow(15),
    K = 64,
    G = 10,
    
)
c.PB
c.beam_type


PB SHAPE (3, 1)
RB SHAPE (3, 3)
B0 SHAPE (3, 1)


<BeamType.Random: 1>

In [20]:
np.arange(5,2)*5 

array([], dtype=int32)

In [21]:
from scipy.spatial.transform import Rotation

Rotation.from_euler('ZYX', np.array([90, 45, 0]).reshape(1, -1).flatten(), degrees=True).as_matrix().shape


(3, 3)

In [22]:
len(np.arange(10).reshape(1, 5, 2).shape)

3

In [23]:
np.arange(6).reshape(2, 3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [24]:
import numpy as np
from src.channel_mmWave_parameters import get_array_layout

get_array_layout(np.array([4, 4]).reshape(-1, 1))

array([[ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ],
       [-1.5, -1.5, -1.5, -1.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,
         0.5,  1.5,  1.5,  1.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5, -1.5, -0.5,  0.5,  1.5, -1.5, -0.5,  0.5,
         1.5, -1.5, -0.5,  0.5,  1.5]])

In [25]:
"""
"""
import numpy as np

def get_array_layout(N_dim: np.ndarray) -> np.ndarray:
    r, c = N_dim
    X, Y = np.meshgrid(np.arange(c) - (c-1)/2, np.arange(r) - (r-1)/2)

    XF = X.ravel(order="F")
    YF = Y.ravel(order="F")
    Z = np.zeros(r*c)

    layout = np.vstack((Z, XF, YF))
    return layout


get_array_layout((2, 4))

array([[ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-1.5, -1.5, -0.5, -0.5,  0.5,  0.5,  1.5,  1.5],
       [-0.5,  0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5]])