In [1]:
import os

using_colab = False
if using_colab:
  os.system('rm -rf ./*')
  os.system('git clone https://github.com/gasparyanartur/radio-optimizer.git')
  os.system('mv radio-optimizer/* ./')
  os.system('rm -rf radio-optimizer')

In [2]:
import numpy as np
from src.channel_mmWave_parameters import ChannelmmWaveParameters

seed = 0
rng = np.random.default_rng(seed)

In [1]:
import numpy as np
from src.utils import db2pow

from src.channel_mmWave_parameters import ChannelmmWaveParameters

c = ChannelmmWaveParameters(
    OB = np.array([45, 0, 0]).reshape(-1, 1),
    NB_dim = np.array([1, 1]).reshape(-1, 1),
    PR = np.array([[-5.01, 2, 0.5], [-1, 5.01, 0.5], [5.01, 2.5, 0.5]]).T,
    OR = np.array([[0, 0, 0], [-90, 0, 0], [180, 0, 0]]).T,
    NR_dim = np.array([[10, 10], [10, 10], [10, 10]]).T,
    PU = np.array([-2, 3, -1.5]).reshape(-1, 1),
    OU = np.array([0, 0, 0]).reshape(-1, 1),
    NU_dim = np.array([1, 1]).reshape(-1, 1),
    P = db2pow(15),
    K = 64,
    G = 10,

    seed=0
)

c.get_beam_matrix()
c.get_tx_symbol()
c.get_path_parameters_PWM()
c.get_FIM_PWM()

fim = c.FIM
c.get_crlb_from_fim_PWM(fim)

c:\Users\gaspa\dev\projects\radio-optimizer\src\channel_mmWave_parameters.py:712: ComplexWarning: Casting complex values to real discards the imaginary part
  H[:, :, k] = ((alpha[k] * Xi[k]) * AstBR) @ AstUR.T     # HR without coeffecients
c:\Users\gaspa\dev\projects\radio-optimizer\src\channel_mmWave_parameters.py:761: ComplexWarning: Casting complex values to real discards the imaginary part
  muBg[:, k] = self.WB.T @ H[:, :, k] * self.XUg[:, k] * ris_g
c:\Users\gaspa\dev\projects\radio-optimizer\src\channel_mmWave_parameters.py:807: ComplexWarning: Casting complex values to real discards the imaginary part
  D_muB[:, :, k, g] = D_muBkg
c:\Users\gaspa\dev\projects\radio-optimizer\src\channel_mmWave_parameters.py:846: ComplexWarning: Casting complex values to real discards the imaginary part
  D_muB[:, :, k, g] = D_muBkg


JS_all.shape
(12, 18)
row_ind, col_ind
[6 7] [3 4 5 6 7]
JS_all[row_ind].shape
(2, 18)
JS_all[row_ind, col_ind]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
J_temp[4:6, :]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
JS_all.shape
(12, 18)
row_ind, col_ind
[8 9] [ 8  9 10 11 12]
JS_all[row_ind].shape
(2, 18)
JS_all[row_ind, col_ind]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
J_temp[4:6, :]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
JS_all.shape
(12, 18)
row_ind, col_ind
[10 11] [13 14 15 16 17]
JS_all[row_ind].shape
(2, 18)
JS_all[row_ind, col_ind]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
J_temp[4:6, :]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [ ]:
c.thetaRU_loc[:, 2]


In [ ]:
c.lambdak