In [3]:
import os

using_colab = False
if using_colab:
  os.system('rm -rf ./*')
  os.system('git clone https://github.com/gasparyanartur/radio-optimizer.git')
  os.system('mv radio-optimizer/* ./')
  os.system('rm -rf radio-optimizer')

In [4]:
import numpy as np
from src.channel_mmWave_parameters import ChannelmmWaveParameters
from src.utils import db2pow

seed = 0
rng = np.random.default_rng(seed)

ImportError: cannot import name 'npa' from 'src.utils' (c:\Users\gaspa\dev\projects\radio-optimizer\src\utils.py)

In [ ]:
c = ChannelmmWaveParameters(
    PB = np.array([1, 2, 3]).T, 
    OB = np.array([45, 0, 0]).T,
    NB_dim = np.array([1, 1]).T,
    PR = np.array([[-5.01, 2, 0.5], [-1, 5.01, 0.5], [5.01, 2.5, 0.5]]).T,
    OR = np.array([[0, 0, 0], [-90, 0, 0], [180, 0, 0]]).T,
    NR_dim = np.array([[10, 10], [10, 10], [10, 10]]).T,
    PU = np.array([-2, 3, -1.5]).T,
    OU = np.array([0, 0, 0]).T,
    NU_dim = np.array([1, 1]).T,
    P = db2pow(15),
    K = 64,
    G = 10,
    
)
c.PB
c.beam_type


<BeamType.Random: 1>

In [ ]:
np.arange(5,2)*5 

array([], dtype=int32)

In [ ]:
from scipy.spatial.transform import Rotation

Rotation.from_euler('ZYX', np.array([90, 45, 0]), degrees=True).as_matrix()


array([[ 0.        , -1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678],
       [-0.70710678,  0.        ,  0.70710678]])

In [ ]:
len(np.arange(10).reshape(1, 5, 2).shape)

3

In [10]:
from src.utils import tp

np.arange(6).reshape(2, 3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [1]:
import numpy as np
from src.get_array_layout import get_array_layout

get_array_layout(np.array([3, 2]))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 4

In [9]:
"""
"""
import numpy as np
from src.utils import tp

def get_array_layout(N_dim: np.ndarray) -> np.ndarray:
    r, c = N_dim
    X, Y = np.meshgrid(np.arange(c) - (c-1)/2, np.arange(r) - (r-1)/2)
    XF = np.hstack(X)
    YF = np.vstack(tp(Y)).T
    print(XF, YF, np.zeros(r*c))
    layout = np.vstack((np.zeros(r*c), XF, YF))
    return layout


get_array_layout((3, 2))

[-0.5  0.5 -0.5  0.5 -0.5  0.5] [[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]] [0. 0. 0. 0. 0. 0.]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 2 has size 2